{{ if eq .Values.helmVersion "3" }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRole
metadata:
  name: {{ include "helm-cabin.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
      - watch
{{ end }}
