{{ if eq .Values.helmVersion "3" }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm-cabin.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helm-cabin.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "helm-cabin.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
